name: dotenv-production-example

on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15
    - name: Nye 
      working-directory: ./dotenv-example
      run: 
        go build && ls
    - name: Run go-dotenv-example
      env:
          ENV: PROD
          FOO: ${{ secrets.SECRET }}
      run: ./go-dotenv-example
